name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'SKIP')"

    steps:
      - uses: actions/checkout@v2
          
      - name: Making ZIP
        run: 7z a -m0=Copy -tzip voxels_blood_p${{ github.run_number }}.zip blood.def bloodgdx.def blood-raze.def license.txt readme.txt MHK KVX DEF
      
      - name: Generating FS files
        run: |
            cd FS
            powershell .\def.ps1
            powershell .\maphacks.ps1
            powershell .\voxels.ps1
          
      - name: Making FS ZIP
        run: 7z a -m0=Copy -tzip voxels_freshsupply_p${{ github.run_number }}.zip ./FS/defs ./FS/KVX ./FS/7za.exe ./FS/fs_install.bat license.txt readme.txt
          
      - name: Deleting older releases
        uses: bubkoo/delete-stale-releases@v1.0.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          keep_latest_count: 0
          delete_tags: true
          exclude: v*
          include: p*
          include_draft: false
          include_prerelease: true
          
      - name: Creating new release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            voxels_blood_p${{ github.run_number }}.zip
            voxels_freshsupply_p${{ github.run_number }}.zip
          release: p${{ github.run_number }}
          prerelease: true
          draft: false
          body: |
            This is a pre-release version of the Blood Voxel Pack that includes all the latest additions and changes
            Use voxels_blood_p${{ github.run_number }}.zip for BloodGDX, NBlood, and Raze
            or voxels_freshsupply_p${{ github.run_number }} for Fresh Supply
